# This is a basic workflow to help you get started with Actions

name: CV to PDF

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  cv2pdf:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Converts CV to PDF
      - uses: baileyjm02/markdown-to-pdf@v1
        with:
          input_dir: ./CV.md
          output_dir: ./pdf
          build_html: false

      # Upload PDF as artifact
      - uses: actions/upload-artifact@v4
        with:
          name: CV
          path: ./pdf/CV.pdf
